CoreTestSupportUtils: fix test framework
It makes no sense to install unsupported key exchange factories. This
makes CipherTest fail on Java 25 when run as part of the sshd-mina (and
probably also sshd-netty) tests, which do not include BouncyCastle.

Without BC, MLKEM is not supported with 2.17.0, but the test uses JSch
as client, which will propose MLKEM when run on Java 25. If the server
includes the unsupported MLKEM KEX in its proposal, this will get
selected and then cause a NoClassDefFoundError exception later in the
Apache MINA SSHD test server, making the test fail.

On Java 21, JSch does not propose MLKEM, so the test worked because the
unsupported KEX algorithm was not selected (curve-25519-sha256 is used
instead).

Simply don't ever install unsupported KEX algorithms.