[releng] Fix surefire config
It made reference to an undefined variable `${workspace.root.folder}`.
Correct would have been `${workspace.root.dir}`, defined in the maven
configuration at .mvn/maven.config.

However, even if corrected running JUnit tests in Eclipse doesn't work
(undefined reference to `session.rootDirectory`) since there is no maven
session.

So fix this differently. As for all our Java projects the maven
workspace root is at `${project.basedir}/..` let's use that. That works
in Eclipse and on the command-line.